---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/21 16:01
---
--local key =KEYS[1]
--local limit = tonumber(ARGV[1])
--local current = tonumber(redis.call('get', key) or "0")
--if current + 1 > limit then
--    return 0
--else
--    redis.call("INCRBY", key, "1");
--    redis.call("expire", key, "2");
--end
--return 1
local key = KEYS[1]
local limit = tonumber(ARGV[1])
local expire_time = ARGV[2]

local is_exists = redis.call("EXISTS", key)
if is_exists == 1 then
    if redis.call("INCR", key) > limit then
        return 0
    else
        return 1
    end
else
    redis.call("SET", key, 1)
    redis.call("EXPIRE", key, expire_time)
    return 1
end